from pathlib import Path

REFERENCE=Path('tools/reference_explanation_renderer.js')
CSS=r'''<style id="physiology-source-visual-css">
.phys-source-explanation{margin-top:12px;display:grid;gap:12px}.phys-source-head{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin:2px 0}.phys-source-page{border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#fff;box-shadow:0 2px 8px rgba(25,27,45,.05);cursor:zoom-in}.phys-source-page img{display:block;width:100%;height:auto;background:#fff}.phys-source-note{font-size:12px;line-height:1.45;color:var(--muted);margin-top:2px}.phys-question-visual{margin-top:12px;padding:12px;border:1px solid #dfe2ec;border-radius:14px;background:#fbfbfe}.phys-question-visual .phys-source-page{margin-top:9px}.phys-zoom-backdrop{position:fixed;inset:0;z-index:9999;background:rgba(10,11,20,.94);display:flex;flex-direction:column;touch-action:none}.phys-zoom-toolbar{height:58px;display:flex;align-items:center;justify-content:space-between;padding:8px 12px;flex:0 0 auto;color:#fff}.phys-zoom-toolbar .phys-zoom-title{font-size:12px;font-weight:750;opacity:.9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-right:10px}.phys-zoom-tools{display:flex;gap:7px}.phys-zoom-tools button{width:38px;height:38px;border:1px solid rgba(255,255,255,.25);border-radius:11px;background:rgba(255,255,255,.1);color:#fff;font-size:20px}.phys-zoom-stage{position:relative;flex:1;overflow:hidden;touch-action:none;display:flex;align-items:center;justify-content:center}.phys-zoom-image{max-width:none;max-height:none;width:auto;height:auto;transform-origin:0 0;user-select:none;-webkit-user-drag:none;touch-action:none}
</style>'''
JS=r'''  function physSourcePages(q){const m=String(q?.sourceRef||'').match(/Solution Pages?\s+(\d+)(?:-(\d+))?/i);if(!m)return[];const a=+m[1],b=+(m[2]||m[1]),o=[];for(let p=a;p<=b;p++)o.push(p);return o;}
  function physQuestionPages(q){if(!q||q.subject!=='Physiology'||!Array.isArray(window.PHYSIOLOGY_IMAGE_PAGES))return[];const a=+q.sourcePage||0,b=+q.sourcePageEnd||a;return window.PHYSIOLOGY_IMAGE_PAGES.filter(p=>p>=a&&p<=b);}
  function physPdfUrl(p){return `https://qbank.local/physiology/pdf?page=${encodeURIComponent(p)}&scale=2.5`;}
  function renderPhysiologySourceExplanation(q){const pages=physSourcePages(q);if(!pages.length)return `<div class="phys-source-note">Original source explanation is not mapped.</div>`;return `<div class="phys-source-explanation"><div class="phys-source-head">Original source explanation</div>${pages.map(p=>`<div class="phys-source-page" onclick="window.QB.openPhysSourceImage(this.querySelector('img'))"><img loading="lazy" src="${physPdfUrl(p)}" alt="Original Physiology explanation, PDF page ${p}" data-source-page="${p}"></div>`).join('')}<div class="phys-source-note">Taken directly from the original Physiology PDF. Tap to open full-screen; pinch, drag, or use +/− to zoom.</div></div>`;}
  function renderPhysiologyQuestionVisual(q){const pages=physQuestionPages(q);if(!pages.length)return'';return `<div class="phys-question-visual"><div class="phys-source-head">Original source figure</div>${pages.map(p=>`<div class="phys-source-page" onclick="window.QB.openPhysSourceImage(this.querySelector('img'))"><img loading="lazy" src="${physPdfUrl(p)}" alt="Original Physiology question source, PDF page ${p}" data-source-page="${p}"></div>`).join('')}<div class="phys-source-note">Original PDF page containing the question figure. Tap to zoom and pan.</div></div>`;}
  let physZoom={scale:1,x:0,y:0,img:null,pointers:new Map(),startDist:0,startScale:1,startX:0,startY:0,baseX:0,baseY:0};
  function applyPhysZoom(){if(physZoom.img)physZoom.img.style.transform=`translate(${physZoom.x}px,${physZoom.y}px) scale(${physZoom.scale})`;}
  function resetPhysZoom(){const i=physZoom.img;if(!i)return;const st=i.parentElement,sx=st.clientWidth/i.naturalWidth,sy=st.clientHeight/i.naturalHeight;physZoom.scale=Math.min(1,Math.min(sx,sy));physZoom.x=(st.clientWidth-i.naturalWidth*physZoom.scale)/2;physZoom.y=(st.clientHeight-i.naturalHeight*physZoom.scale)/2;applyPhysZoom();}
  function openPhysSourceImage(img){if(!img)return;closePhysSourceImage();const b=document.createElement('div');b.id='phys-zoom-backdrop';b.className='phys-zoom-backdrop';b.innerHTML=`<div class="phys-zoom-toolbar"><div class="phys-zoom-title">Original source · PDF page ${esc(img.getAttribute('data-source-page')||'')}</div><div class="phys-zoom-tools"><button id="pz-minus">−</button><button id="pz-reset">1×</button><button id="pz-plus">+</button><button id="pz-close">×</button></div></div><div class="phys-zoom-stage"><img class="phys-zoom-image" src="${img.src}" alt="${esc(img.alt||'Original source')}"></div>`;document.body.appendChild(b);const st=b.querySelector('.phys-zoom-stage'),i=b.querySelector('.phys-zoom-image');physZoom={scale:1,x:0,y:0,img:i,pointers:new Map(),startDist:0,startScale:1,startX:0,startY:0,baseX:0,baseY:0};i.addEventListener('load',()=>resetPhysZoom());b.querySelector('#pz-close').onclick=closePhysSourceImage;b.querySelector('#pz-reset').onclick=resetPhysZoom;b.querySelector('#pz-plus').onclick=()=>{physZoom.scale=Math.min(5,physZoom.scale*1.35);applyPhysZoom();};b.querySelector('#pz-minus').onclick=()=>{physZoom.scale=Math.max(.5,physZoom.scale/1.35);applyPhysZoom();};st.addEventListener('pointerdown',e=>{st.setPointerCapture?.(e.pointerId);physZoom.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(physZoom.pointers.size===1){physZoom.startX=e.clientX;physZoom.startY=e.clientY;physZoom.baseX=physZoom.x;physZoom.baseY=physZoom.y;}else{const ps=[...physZoom.pointers.values()];physZoom.startDist=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);physZoom.startScale=physZoom.scale;}});st.addEventListener('pointermove',e=>{if(!physZoom.pointers.has(e.pointerId))return;physZoom.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const ps=[...physZoom.pointers.values()];if(ps.length===1){physZoom.x=physZoom.baseX+e.clientX-physZoom.startX;physZoom.y=physZoom.baseY+e.clientY-physZoom.startY;applyPhysZoom();}else if(ps.length===2&&physZoom.startDist){const d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);physZoom.scale=Math.max(.5,Math.min(5,physZoom.startScale*d/physZoom.startDist));applyPhysZoom();}});['pointerup','pointercancel','pointerleave'].forEach(ev=>st.addEventListener(ev,e=>physZoom.pointers.delete(e.pointerId)));b.addEventListener('click',e=>{if(e.target===b)closePhysSourceImage();});}
  function closePhysSourceImage(){document.getElementById('phys-zoom-backdrop')?.remove();physZoom={scale:1,x:0,y:0,img:null,pointers:new Map(),startDist:0,startScale:1,startX:0,startY:0,baseX:0,baseY:0};}
  window.QB.openPhysSourceImage=openPhysSourceImage;window.QB.closePhysSourceImage=closePhysSourceImage;
'''

def patch_html(s):
    a=s.index('  function richText(text) {'); b=s.index('\n  function practiceHistory',a)
    renderer=REFERENCE.read_text(encoding='utf8')
    renderer=renderer.replace("  function renderExplanationText(text,question){\n    if(!text) return '';", "  function renderExplanationText(text,question){\n    if(question && question.subject==='Physiology') return renderPhysiologySourceExplanation(question);\n    if(!text) return '';")
    s=s[:a]+renderer+'\n'+JS+s[b:]
    if 'physiology-source-visual-css' not in s:s=s.replace('</head>',CSS+'\n</head>',1)
    if 'assets/physiology_image_pages.js' not in s:s=s.replace('</script>\n<script>(() => {','</script>\n<script src="assets/physiology_image_pages.js"></script>\n<script>(() => {',1)
    old="const sourceImg=IMAGE_PAGES.has(q.sourcePage) ? `<div class=\"source-preview\"><img loading=\"lazy\" src=\"assets/source_pages/p${String(q.sourcePage).padStart(3,'0')}.png\" alt=\"Original source PDF page ${q.sourcePage}\"></div>` : '';"
    new="const sourceImg=q.subject==='Physiology'?renderPhysiologyQuestionVisual(q):(IMAGE_PAGES.has(q.sourcePage) ? `<div class=\"source-preview\"><img loading=\"lazy\" src=\"assets/source_pages/p${String(q.sourcePage).padStart(3,'0')}.png\" alt=\"Original source PDF page ${q.sourcePage}\"></div>` : '');"
    s=s.replace(old,new)
    return s

if __name__=='__main__':
    pdf=Path('app/src/main/assets/Physiology_QBank_Source.pdf')
    if not pdf.exists(): raise SystemExit('Physiology source PDF missing: add app/src/main/assets/Physiology_QBank_Source.pdf before building this source-visual version.')
    p=Path('app/src/main/assets/index.html')
    p.write_text(patch_html(p.read_text(encoding='utf8')),encoding='utf8')
    print('Applied source-PDF renderer; QBank data left untouched.')
