from pathlib import Path

HTML=Path('app/src/main/assets/index.html')
s=HTML.read_text(encoding='utf-8')

css=r'''<style id="v104-design-system">
:root{--v-bg:#f5f7fb;--v-surface:rgba(255,255,255,.94);--v-text:#152033;--v-muted:#68758a;--v-primary:#315bea;--v-primary-2:#6d4df5;--v-success:#16a36a;--v-danger:#df4d63;--v-warning:#e49a28;--v-border:rgba(25,39,68,.09);--v-shadow:0 14px 40px rgba(25,39,68,.08);--v-radius:20px}
*{box-sizing:border-box}html{background:var(--v-bg)}body{margin:0;background:radial-gradient(circle at 10% 0%,rgba(49,91,234,.08),transparent 34%),radial-gradient(circle at 90% 10%,rgba(109,77,245,.07),transparent 30%),var(--v-bg);color:var(--v-text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}
.topbar{position:sticky;top:0;z-index:30;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);background:rgba(245,247,251,.78)!important;border-bottom:1px solid var(--v-border)!important;min-height:64px!important}
.brand{font-weight:900!important;letter-spacing:-.03em}.page{max-width:1120px!important;margin:0 auto;padding:24px 18px 42px!important}.page-title{font-size:clamp(28px,5vw,40px)!important;letter-spacing:-.045em!important;font-weight:900!important}.page-sub,.crumb,.label{color:var(--v-muted)!important}.card{background:var(--v-surface)!important;border:1px solid var(--v-border)!important;border-radius:var(--v-radius)!important;box-shadow:var(--v-shadow)!important;transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease}.card:hover{transform:translateY(-2px);box-shadow:0 20px 50px rgba(25,39,68,.11)!important}
.primary-btn,.ghost-btn{border-radius:14px!important;min-height:46px!important;font-weight:800!important;transition:transform .16s ease,filter .16s ease,box-shadow .16s ease!important}.primary-btn{background:linear-gradient(135deg,var(--v-primary),var(--v-primary-2))!important;box-shadow:0 8px 20px rgba(49,91,234,.22)!important;border:0!important}.primary-btn:active,.ghost-btn:active,.option:active{transform:scale(.98)}.ghost-btn{background:rgba(255,255,255,.72)!important;border:1px solid var(--v-border)!important;color:var(--v-text)!important}
.option-list{gap:12px!important}.option{border:1px solid var(--v-border)!important;border-radius:16px!important;background:rgba(255,255,255,.82)!important;min-height:58px!important;padding:14px 16px!important;transition:all .18s ease!important}.option:hover{border-color:rgba(49,91,234,.28)!important;transform:translateY(-1px)}.option.selected{box-shadow:0 8px 22px rgba(49,91,234,.10)!important}.option.correct{border-color:rgba(22,163,106,.38)!important;background:rgba(22,163,106,.08)!important}.option.wrong{border-color:rgba(223,77,99,.38)!important;background:rgba(223,77,99,.07)!important}
.feedback{border-radius:16px!important;border:1px solid var(--v-border)!important}.q-footer{gap:10px!important}.mode-pill{display:inline-flex!important;border-radius:999px!important;padding:7px 11px!important;background:rgba(49,91,234,.10)!important;color:var(--v-primary)!important;font-weight:850!important;font-size:12px!important;letter-spacing:.03em}
.v104-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:20px 0}.v104-card{padding:20px;min-height:120px;position:relative;overflow:hidden}.v104-card:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-35px;top:-35px;background:linear-gradient(135deg,rgba(49,91,234,.12),rgba(109,77,245,.03))}.v104-kicker{font-size:12px;font-weight:850;text-transform:uppercase;letter-spacing:.07em;color:var(--v-muted)}.v104-value{font-size:27px;font-weight:900;letter-spacing:-.04em;margin-top:7px}.v104-action{display:flex;align-items:center;justify-content:space-between;gap:12px}.v104-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,rgba(49,91,234,.13),rgba(109,77,245,.10));font-size:20px}.v104-backup{margin-top:16px;padding:18px;display:flex;align-items:center;justify-content:space-between;gap:16px}.v104-backup small{display:block;color:var(--v-muted);margin-top:4px}.v104-backup-actions{display:flex;gap:8px;flex-wrap:wrap}.v104-modal{position:fixed;inset:0;z-index:100;background:rgba(10,18,35,.42);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:14px}.v104-sheet{width:min(620px,100%);background:#fff;border-radius:24px;padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.2);animation:v104up .22s ease}.v104-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid var(--v-border)}.v104-row:last-child{border-bottom:0}@keyframes v104up{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}@media(max-width:680px){.v104-grid{grid-template-columns:1fr}.v104-backup{align-items:flex-start;flex-direction:column}.v104-backup-actions{width:100%}.v104-backup-actions button{flex:1}}
</style>'''
js=r'''<script id="v104-ui-runtime">
(function(){'use strict';
function state(){try{if(window.QB&&window.QB.getState)return window.QB.getState()||{};}catch(e){}try{return JSON.parse(localStorage.getItem('qbank_state_v1')||'{}')}catch(e){return {}}}
function saveBlob(){var st=state(),payload={backupVersion:1,app:'QBank',createdAt:new Date().toISOString(),state:st};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});var name='QBank_Backup_'+new Date().toISOString().slice(0,10)+'.qbbackup';if(navigator.share&&window.File){try{var f=new File([blob],name,{type:'application/json'});navigator.share({title:'QBank Backup',files:[f]});return;}catch(e){}}var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1500)}
function restoreFile(input){var f=input.files&&input.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var p=JSON.parse(r.result);if(!p||p.app!=='QBank'||Number(p.backupVersion)!==1||!p.state)throw Error('Invalid backup');if(!confirm('Restore this QBank backup? Current app history will be replaced.'))return;localStorage.setItem('qbank_state_v1',JSON.stringify(p.state));alert('Backup restored. The app will reload.');location.reload()}catch(e){alert('This backup could not be restored.')}};r.readAsText(f)}
function backupModal(){var m=document.createElement('div');m.className='v104-modal';m.innerHTML='<div class="v104-sheet"><div style="display:flex;justify-content:space-between;align-items:center"><div><div class="v104-kicker">Data safety</div><h2 style="margin:5px 0 0;font-size:25px">Backup & Restore</h2></div><button class="ghost-btn" id="v104-close">Close</button></div><div class="v104-row"><div><b>Backup now</b><small style="display:block;color:var(--v-muted)">Save all progress, bookmarks, tests, statistics and history.</small></div><button class="primary-btn" id="v104-save">Backup</button></div><div class="v104-row"><div><b>Restore backup</b><small style="display:block;color:var(--v-muted)">Import a previously saved .qbbackup file.</small></div><label class="ghost-btn" style="display:grid;place-items:center;cursor:pointer">Restore<input id="v104-file" type="file" accept=".qbbackup,.json,application/json" style="display:none"></label></div><div class="v104-row"><div><b>Automatic backup</b><small style="display:block;color:var(--v-muted)">V10.4 keeps a versioned local safety snapshot. Cloud Drive sync is isolated for the next native backup layer.</small></div><select id="v104-auto" style="padding:10px;border-radius:12px;border:1px solid var(--v-border)"><option>Off</option><option>Every 3 days</option><option>Weekly</option></select></div></div>';document.body.appendChild(m);m.querySelector('#v104-close').onclick=function(){m.remove()};m.querySelector('#v104-save').onclick=saveBlob;m.querySelector('#v104-file').onchange=function(){restoreFile(this)};var pref=localStorage.getItem('qbank_backup_schedule_v1')||'Off';m.querySelector('#v104-auto').value=pref;m.querySelector('#v104-auto').onchange=function(){localStorage.setItem('qbank_backup_schedule_v1',this.value);if(this.value!=='Off')localStorage.setItem('qbank_auto_snapshot_v1',JSON.stringify({backupVersion:1,app:'QBank',createdAt:new Date().toISOString(),state:state()}))}}
function enhance(){if(document.querySelector('.v104-backup'))return;var app=document.getElementById('app');if(!app)return;var page=document.querySelector('.page');if(!page)return;var h=page.querySelector('.page-head');if(!h)return;var grid=document.createElement('div');grid.className='v104-grid';grid.innerHTML='<div class="card v104-card"><div class="v104-action"><div><div class="v104-kicker">Study</div><div class="v104-value">Practice</div><div style="color:var(--v-muted);margin-top:4px">Keep your momentum going.</div></div><div class="v104-icon">✦</div></div></div><div class="card v104-card"><div class="v104-action"><div><div class="v104-kicker">Performance</div><div class="v104-value">Your progress</div><div style="color:var(--v-muted);margin-top:4px">Accuracy, streaks and activity.</div></div><div class="v104-icon">↗</div></div></div>';h.insertAdjacentElement('afterend',grid);var b=document.createElement('div');b.className='card v104-backup';b.innerHTML='<div><b>Protect your progress</b><small>Back up bookmarks, attempts, tests and study history.</small></div><div class="v104-backup-actions"><button class="ghost-btn" id="v104-backup-btn">Backup & Restore</button></div>';page.appendChild(b);b.querySelector('button').onclick=backupModal}
new MutationObserver(function(){enhance()}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(enhance,250);
window.QB=window.QB||{};window.QB.openBackup=backupModal;window.QB.exportBackup=saveBlob;
})();
</script>'''
if 'id="v104-design-system"' not in s:s=s.replace('</head>',css+'\n</head>',1)
if 'id="v104-ui-runtime"' not in s:s=s.replace('</body>',js+'\n</body>',1)
HTML.write_text(s,encoding='utf-8')
print('V10.4 UI + backup layer installed')