from pathlib import Path

HTML=Path('app/src/main/assets/index.html')
s=HTML.read_text(encoding='utf-8')

css=r'''<style id="v105-experience">
:root{--v5-ink:#152033;--v5-muted:#68758a;--v5-line:rgba(25,39,68,.09);--v5-blue:#315bea;--v5-violet:#7257e8;--v5-mint:#16a36a;--v5-rose:#df4d63;--v5-amber:#e49a28}
.v105-cockpit{margin:16px 0 20px;padding:20px;border-radius:24px;background:linear-gradient(135deg,rgba(49,91,234,.11),rgba(114,87,232,.08) 55%,rgba(22,163,106,.08));border:1px solid var(--v5-line);box-shadow:0 16px 44px rgba(25,39,68,.07);overflow:hidden;position:relative}
.v105-cockpit:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-65px;top:-80px;background:rgba(114,87,232,.10)}
.v105-eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.09em;font-weight:900;color:var(--v5-muted)}
.v105-cockpit h2{margin:5px 0 3px;font-size:25px;letter-spacing:-.04em}.v105-cockpit p{margin:0;color:var(--v5-muted);font-size:13px}
.v105-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px;position:relative;z-index:1}.v105-actions button{min-width:132px}
.v105-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:15px;position:relative;z-index:1}.v105-metric{padding:12px 13px;border-radius:15px;background:rgba(255,255,255,.66);border:1px solid rgba(25,39,68,.06)}.v105-metric strong{display:block;font-size:20px;letter-spacing:-.03em}.v105-metric span{font-size:10px;font-weight:800;color:var(--v5-muted)}
.v105-subjects{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:0 0 20px}.v105-subject{padding:17px;border-radius:20px;background:rgba(255,255,255,.86);border:1px solid var(--v5-line);box-shadow:0 10px 30px rgba(25,39,68,.055);cursor:pointer;transition:transform .18s ease,box-shadow .18s ease}.v105-subject:active{transform:scale(.985)}.v105-subject-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.v105-dot{width:10px;height:10px;border-radius:50%;background:var(--v5-blue);box-shadow:0 0 0 5px rgba(49,91,234,.09)}.v105-subject:nth-child(2) .v105-dot{background:var(--v5-violet);box-shadow:0 0 0 5px rgba(114,87,232,.09)}.v105-subject:nth-child(3) .v105-dot{background:var(--v5-mint);box-shadow:0 0 0 5px rgba(22,163,106,.09)}.v105-subject b{font-size:16px}.v105-subject small{display:block;color:var(--v5-muted);margin-top:7px;line-height:1.4}.v105-progress{height:6px;border-radius:999px;background:rgba(25,39,68,.07);overflow:hidden;margin-top:12px}.v105-progress i{display:block;height:100%;width:0;border-radius:inherit;background:linear-gradient(90deg,var(--v5-blue),var(--v5-violet));transition:width .5s ease}
.v105-sheet{max-height:86vh;overflow:auto}.v105-analytics-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.v105-analysis-card{padding:15px;border:1px solid var(--v5-line);border-radius:17px;background:#fafbfe}.v105-analysis-card strong{font-size:23px;display:block}.v105-bar{height:9px;border-radius:99px;background:#e9edf4;overflow:hidden;margin-top:8px}.v105-bar i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--v5-blue),var(--v5-violet))}.v105-topic{display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid var(--v5-line)}.v105-topic:last-child{border-bottom:0}.v105-topic b{font-size:13px;flex:1}.v105-topic span{font-size:11px;color:var(--v5-muted);font-weight:800}
.v105-qhead{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.v105-progress-pill{display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border-radius:999px;background:rgba(49,91,234,.09);color:var(--v5-blue);font-size:11px;font-weight:900}.v105-option-hint{font-size:11px;color:var(--v5-muted);margin:0 0 8px}.v105-option-letter{width:29px;height:29px;border-radius:10px;display:inline-grid;place-items:center;font-weight:900;background:rgba(49,91,234,.08);color:var(--v5-blue);margin-right:10px;flex:0 0 auto}
@media(max-width:720px){.v105-metrics{grid-template-columns:1fr 1fr}.v105-subjects{grid-template-columns:1fr}.v105-analytics-grid{grid-template-columns:1fr}.v105-actions button{flex:1;min-width:0}}
</style>'''

js=r'''<script id="v105-runtime">
(function(){'use strict';
var INST='v105-runtime';
function read(){try{if(window.QB&&window.QB.getState)return window.QB.getState()||{};}catch(e){}try{return JSON.parse(localStorage.getItem('qbank_state_v1')||'{}')}catch(e){return {}}}
function allQuestions(){var out=[];['window.BIOCHEM_QUESTIONS','window.SUBJECT_QUESTIONS'].forEach(function(x){});try{if(Array.isArray(window.questions))out=out.concat(window.questions)}catch(e){}try{if(Array.isArray(window.BY_ID))out=out.concat(window.BY_ID)}catch(e){}return out}
function tests(st){return Array.isArray(st.tests)?st.tests:[]}
function attemptMap(st){var a={};var src=st.attempts||st.history||[];if(Array.isArray(src))src.forEach(function(x){var id=x.questionId||x.id;if(id)a[id]=x});else if(src&&typeof src==='object')Object.keys(src).forEach(function(k){a[k]=src[k]});return a}
function stats(){var st=read(),ts=tests(st),attempts=attemptMap(st),answered=Object.keys(attempts).length,correct=0,total=0;Object.keys(attempts).forEach(function(k){var x=attempts[k];if(x&&((x.correct===true)||Number(x.isCorrect)===1))correct++;total++});ts.forEach(function(t){if(typeof t.correct==='number'){correct+=t.correct;total+=Number(t.total||0)}});var acc=total?Math.round(correct/total*100):0;var streak=Number(st.streak||(st.stats&&st.stats.streak)||0);return {st:st,answered:answered,tests:ts.length,correct:correct,total:total,accuracy:acc,streak:streak}}
function findPage(){return document.querySelector('.page')}
function button(label,cls){var b=document.createElement('button');b.className=cls||'ghost-btn';b.textContent=label;return b}
function dashboard(){if(document.querySelector('.v105-cockpit'))return;var page=findPage();if(!page)return;var head=page.querySelector('.page-head');if(!head)return;var x=stats(),box=document.createElement('section');box.className='v105-cockpit';box.innerHTML='<div class="v105-eyebrow">V10.5 · intelligent study cockpit</div><h2>Study with a plan, not a guess.</h2><p>Your QBank should tell you what matters next.</p><div class="v105-metrics"><div class="v105-metric"><strong>'+x.answered+'</strong><span>questions attempted</span></div><div class="v105-metric"><strong>'+x.accuracy+'%</strong><span>tracked accuracy</span></div><div class="v105-metric"><strong>'+x.tests+'</strong><span>tests saved</span></div><div class="v105-metric"><strong>'+x.streak+'</strong><span>day streak</span></div></div><div class="v105-actions"><button class="primary-btn" id="v105-practice">Continue Practice</button><button class="ghost-btn" id="v105-analytics">View Analytics</button></div>';head.insertAdjacentElement('afterend',box);box.querySelector('#v105-practice').onclick=function(){try{if(window.QB&&window.QB.startPractice)return window.QB.startPractice()}catch(e){}try{location.hash='#practice'}catch(e){}};box.querySelector('#v105-analytics').onclick=analytics}
function subjectCards(){if(document.querySelector('.v105-subjects'))return;var page=findPage();if(!page)return;var head=page.querySelector('.page-head');if(!head)return;var wrap=document.createElement('section');wrap.className='v105-subjects';var data=[['Biochemistry','Core metabolism, enzymes & molecular medicine','biochemistry'],['Physiology','Systems, regulation & mechanisms','physiology'],['Anatomy','Regional anatomy & clinical relations','anatomy']];wrap.innerHTML=data.map(function(d,i){return '<div class="v105-subject" data-subject="'+d[2]+'"><div class="v105-subject-top"><b>'+d[0]+'</b><i class="v105-dot"></i></div><small>'+d[1]+'</small><div class="v105-progress"><i></i></div><small>Open subject →</small></div>'}).join('');var anchor=document.querySelector('.v105-cockpit')||head;anchor.insertAdjacentElement('afterend',wrap);wrap.querySelectorAll('.v105-subject').forEach(function(card){card.onclick=function(){var s=this.getAttribute('data-subject');try{if(window.QB&&window.QB.openSubject){window.QB.openSubject(s);return}}catch(e){}try{location.hash='#'+s}catch(e){}}})}
function analytics(){var old=document.querySelector('.v105-modal');if(old)old.remove();var x=stats(),m=document.createElement('div');m.className='v104-modal v105-modal';m.innerHTML='<div class="v104-sheet v105-sheet"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><div class="v105-eyebrow">Performance</div><h2 style="margin:4px 0">Your study analytics</h2></div><button class="ghost-btn" id="v105-close">Close</button></div><div class="v105-analytics-grid"><div class="v105-analysis-card"><span>Accuracy</span><strong>'+x.accuracy+'%</strong><div class="v105-bar"><i style="width:'+x.accuracy+'%"></i></div></div><div class="v105-analysis-card"><span>Questions</span><strong>'+x.answered+'</strong><div style="color:var(--v5-muted);font-size:11px;margin-top:4px">unique attempted</div></div><div class="v105-analysis-card"><span>Tests</span><strong>'+x.tests+'</strong><div style="color:var(--v5-muted);font-size:11px;margin-top:4px">saved assessments</div></div><div class="v105-analysis-card"><span>Streak</span><strong>'+x.streak+'</strong><div style="color:var(--v5-muted);font-size:11px;margin-top:4px">consecutive study days</div></div></div><h3 style="margin:18px 0 7px">Recent test performance</h3><div>'+tests(x.st).slice(-6).reverse().map(function(t){var a=Number(t.total||0)?Math.round(Number(t.correct||0)/Number(t.total)*100):0;return '<div class="v105-topic"><b>'+String(t.title||'Test').replace(/</g,'&lt;')+'</b><span>'+a+'% · '+Number(t.total||0)+' Q</span></div>'}).join('')||'<div style="color:var(--v5-muted);padding:10px 0">Complete a test to see performance here.</div>'+'</div></div>';document.body.appendChild(m);m.querySelector('#v105-close').onclick=function(){m.remove()}}
function questionPolish(){var app=document.getElementById('app');if(!app||!document.querySelector('.question-card')&&!document.querySelector('.option-list'))return;var list=document.querySelector('.option-list');if(list&&!list.querySelector('.v105-option-hint')){var h=document.createElement('p');h.className='v105-option-hint';h.textContent='Select the best answer';list.parentNode.insertBefore(h,list)}document.querySelectorAll('.option').forEach(function(o,i){if(o.querySelector('.v105-option-letter'))return;var l=document.createElement('span');l.className='v105-option-letter';l.textContent=String.fromCharCode(65+i);o.insertBefore(l,o.firstChild)});var q=document.querySelector('.question-card');if(q&&!q.querySelector('.v105-qhead')){var h=q.querySelector('h1,h2,.question-title');if(h){var row=document.createElement('div');row.className='v105-qhead';h.parentNode.insertBefore(row,h);row.appendChild(h);var pill=document.createElement('span');pill.className='v105-progress-pill';pill.textContent='Question';row.appendChild(pill)}}}
function tick(){try{if(location.hash==='#dashboard'||location.hash===''||location.hash==='#')dashboard();}catch(e){}subjectCards();questionPolish()}
new MutationObserver(function(){setTimeout(tick,20)}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(tick,300);window.QB=window.QB||{};window.QB.openAnalytics=analytics;
})();
</script>'''

if 'id="v105-experience"' not in s:s=s.replace('</head>',css+'\n</head>',1)
if 'id="v105-runtime"' not in s:s=s.replace('</body>',js+'\n</body>',1)
HTML.write_text(s,encoding='utf-8')
print('V10.5 QBank experience layer installed')
